# Generated by Django 5.2.3 on 2025-07-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_selected',
        ),
    ]
